apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: config.loki.grafana.com/v1
    kind: ProjectConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: :8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: false
    builtInCertManagement:
      enabled: true
    featureGates:
      #
      # Encryption feature gates
      #
      httpEncryption: false
      grpcEncryption: false
      #
      # Component feature gates
      #
      lokiStackGateway: false
      runtimeSeccompProfile: true
      #
      # Webhook feature gates
      #
      lokiStackWebhook: false
      alertingRuleWebhook: false
      recordingRuleWebhook: false
      rulerConfigWebhook: false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: loki-operator
    app.kubernetes.io/version: 0.0.1
  name: manager-config
  namespace: logging
