apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: loki-operator
    app.kubernetes.io/version: 0.0.1
  name: controller-manager-metrics-service
  namespace: logging
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: loki-operator
    name: loki-operator-controller-manager
