apiVersion: apps/v1
kind: Deployment
metadata:
  name: korrel8r
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: korrel8r
  template:
    metadata:
      labels:
        app.kubernetes.io/name: korrel8r
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: korrel8r
      containers:
      - name: korrel8r
        image: "quay.io/korrel8r/korrel8r"
        imagePullPolicy: Always
        command:
          - "korrel8r"
          - "web"
          - "--verbose=2"
          - "--https=:8443"
          - "--cert=/etc/secrets/tls.crt"
          - "--key=/etc/secrets/tls.key"
          - "--config=/etc/korrel8r/openshift-svc.yaml"
        volumeMounts:
          - name: secrets
            readOnly: true
            mountPath: /etc/secrets
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
