apiVersion: v1
kind: Service
metadata:
  name: korrel8r
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: korrel8r
spec:
  ports:
  - name: https
    port: 8443
    targetPort: 8443
  selector:
