#!/usr/bin/env python3
"""
Script to export analysis results to document
Run this after getting analysis from your app
"""

import subprocess
import json
from datetime import datetime

def export_pod_analysis(pod_name, namespace, output_format="markdown"):
    """Export pod analysis to document"""
    
    # Get pod analysis (you can modify this to get from your app)
    analysis_cmd = f"oc describe pod {pod_name} -n {namespace}"
    result = subprocess.run(analysis_cmd.split(), capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"Error getting pod info: {result.stderr}")
        return
    
    pod_info = result.stdout
    
    # Create document content
    if output_format == "markdown":
        doc_content = f"""# Pod Analysis Report

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Pod:** {pod_name}
**Namespace:** {namespace}

## Pod Information

```
{pod_info}
```

## Analysis Notes

*Add your analysis notes here*

---
*Generated by OpenShift Troubleshooter Export Script*
"""
    
    elif output_format == "html":
        doc_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>Pod Analysis Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        .header {{ background-color: #f0f0f0; padding: 20px; border-radius: 5px; }}
        .content {{ margin-top: 20px; }}
        pre {{ background-color: #f5f5f5; padding: 15px; border-radius: 5px; overflow-x: auto; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Pod Analysis Report</h1>
        <p><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        <p><strong>Pod:</strong> {pod_name}</p>
        <p><strong>Namespace:</strong> {namespace}</p>
    </div>
    
    <div class="content">
        <h2>Pod Information</h2>
        <pre>{pod_info}</pre>
        
        <h2>Analysis Notes</h2>
        <p><em>Add your analysis notes here</em></p>
    </div>
</body>
</html>"""
    
    # Save to file
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    filename = f"pod-analysis-{pod_name}-{timestamp}.{output_format}"
    
    with open(filename, 'w', encoding='utf-8') as f:
        f.write(doc_content)
    
    print(f"Analysis exported to: {filename}")
    return filename

# Usage example:
if __name__ == "__main__":
    # Export analysis for crash-loop-test pod
    export_pod_analysis("crash-loop-test", "default", "markdown")
    export_pod_analysis("crash-loop-test", "default", "html")
