apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: troubleshooting-panel
  annotations:
    observability.openshift.io/api-support: GeneralAvailability
spec:
  type: TroubleshootingPanel
