name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          # Note:  version here should match the one in ../../go.mod
          go-version: '1.24'

      - name: lint
        uses: golangci/golangci-lint-action@v7
        with:
          # Note: version here should match the one in ../../.bingo/golangci-lint.mod
          version: 'v2.1.5'
          args: "--timeout=3m"

      - name: test
        run: make test-no-cluster
